version: '3.0'

services:
  backend:
    build:
      context: backend
      dockerfile: GrpcChat.Web/Dockerfile
    ports:
      - '8080:80'
    environment:
      JWT__KEY: 'hello, world, this is me'
      JWT__ISSUER: 'dungeon master'
      JWT__AUDIENCE: 'http://localhost:8080'
      
      DATABASE__CONNECTION_STRING: 'Host=postgres;Database=postgres;User Id=postgres;Password=postgres;Port=5432'
    
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    
volumes:
  postgres-volume:
    driver: local
    
    